### PR TITLE
Travis changes to begin testing.

### PR DESCRIPTION
**Pull request by amitjamadagni**
Uncomment the testing part in travis file.

### CODE REVIEW

**Comment by i2000s** [comment]
Sorry, it just passed my test on initializing. See #11 And yeah, we need the testing part.

**Comment by amitjamadagni** [comment]
The PR addresses the testing part. This was commented in the PR #8, though there is nothing much to test when additional functionality is added we do not need to re edit again. And also #11 adds a badge  and does not trigger the build of the package and thereby testing the package.

**Comment by amitjamadagni** [comment]
Also let us stick to the version 0.4, allowing the build on 0.5 to fail.

**Comment by amitjamadagni** [comment]
Travis works ! Squashing and merging ...

**Comment by i2000s** [comment]
Sure. Move on to v0.5 next month.

**Comment by quantshah** [comment]
Okay, so can the branches be deleted and the PR's closed ? So many things happening in parallel. :confused:

**Comment by amitjamadagni** [comment]
@sahmed95 once travis CI passes and it is reviewed, it is ready to be merged and once merged we can delete the branch as the branch is specific to the user creating the PR. PR's merged automatically tagged as closed.

**Comment by quantshah** [comment]
Okay !

**Pull request merged**
