### PR TITLE
Initial

### PR DESCRIPTION
**Pull request by Roger-luo**

### CODE REVIEW

**Comment by amitjamadagni** [comment]
How about squashing on this ?! 
On the current branch what does git rebase -i HEAD~4 (implying the last four commits) give ?!

**Comment by Roger-luo** [comment]
fatal: Needed a single revision
invalid upstream HEAD~4

**Comment by Roger-luo** [comment]
@amitjamadagni  Done...

**Comment by amitjamadagni** [comment]
Great ! I hope this is fine now ... go ahead and merge the pull request ! 

Also once that is done, rebase your master to be in sync with the main master (currently the master on your fork is not in sync with the master of the main repo). Look at this answer 

http://stackoverflow.com/a/7244456/5876116

**Pull request merged**
