### PR TITLE
Generate necessary files for Julia package (travis.yml, appveyor.yml, tests etc.) 

### PR DESCRIPTION
**Pull request by quantshah**
Used PkgDev.generate("QuCmp", "MIT") to generate the necessary structure for a Julia package. These files should be present for configuring tests and travis/appveyor builds.

### CODE REVIEW

**Comment by quantshah** [comment]
@amitjamadagni @Roger-luo I believe these files should be added as part of the structure of the Julia Package. They are necessary for configuring tests on Travis.

**Comment by i2000s** [comment]
Should we merge this first? Seems overlaps with other PRs can be corrected later.

**Comment by Roger-luo** [comment]
I generated some of those files before :-) and sure I think we can merge it. What do you think? @amitjamadagni 

BTW, what should the license author be here in the license? It seems the Pkg.generate would add the git user as its default author. Should we change it to JuliaQuantum?

**Comment by amitjamadagni** [comment]
I would wait till the repo name is changed and merge this PR first. Though there is some overlap between other PR's and this, in the review process of other PR's we can be careful with the overlap. Also regarding the review, I reviewed some of the PR's while I was at JuliaCon but then I could not make much progress though I seem to understand the flow of the package. Anyway let me try and keep you updated on the review.

Regarding the licence, is this with respect to this PR ?! If so could you comment on the specific line.

**Comment by i2000s** [comment]
@amitjamadagni Are you sure changing the repo name won't break the PR? I was thinking merging before changing the name to be safe.

**Comment by i2000s** [comment]
@Roger-luo For the authors, I suggest to use "Contributors to QuCmp.jl" with a link to the contributors' page. That way you don't need to update the list every once a while.

**Comment by i2000s** [comment]
@Roger-luo please fix any overlaps with your latest changes, like the contributors/authors.

**Pull request merged**
